@startuml

title (UGA1) 강좌 정보 상단에서 기본 정보를 조회할 수 있다.

actor "강의자"

box "구름 강좌 홈 메뉴"
participant "강좌 홈 - 메인"
participant "강좌 홈 - 강좌 정보 조회"
endbox

"강의자" -> "강좌 홈 - 메인" : 강좌 홈 버튼 선택

group 강좌 정보를 조회하는 경우
"강의자" -> "강좌 홈 - 강좌 정보 조회" : 접근
"강좌 홈 - 강좌 정보 조회" --> "강의자" : 강좌의 기본 정보 및 강좌 소개 정보를 표시

group (유형1) 기본 정보 영역의 경우
"강좌 홈 - 강좌 정보 조회" --> "강의자" : [강의자명, 카테고리, 난이도, 수강인원, 평균 평점, 강좌 추천 대상, 강좌 썸네일, 태그] 제공
end

group (유형2) 강좌 소개 영역의 경우
"강좌 홈 - 강좌 정보 조회" --> "강의자" : [수업 소개, 학습 목표, 참고사항, 강의자 소개 등 강의자가 노출시키고자 하는 강좌 관련 소개글] 제공
end
end

@enduml