@startuml

title 1. 관리자 페이지 내 출결 관리 기능

actor "채널 관리자"

box "구름 내부모듈"
participant "강의 별 출결 페이지"
participant "구름 출결 본인인증 시스템"
endbox

box "외부 시스템"
participant "한국산업인력공단 시스템"
endbox

alt 기능 1. 강좌 내 강의별 출결기록 조회 기능 (출결과 개인정보 조회)
"채널 관리자" -> "강의 별 출결 페이지" : 조회
"강의 별 출결 페이지" -> "구름 출결 본인인증 시스템": 강의 별 수강생 출결 정보 요청
"구름 출결 본인인증 시스템" --> "강의 별 출결 페이지" : 강의 별 수강생 출결 정보 제공
"강의 별 출결 페이지" --> "채널 관리자": 수강생 별 출결 정보, 휴대폰 번호, 이름 제공
end

alt 기능 2. 한국산업인력공단으로 출결 내역을 제출 기능
"채널 관리자" -> "강의 별 출결 페이지" : 한국산업인력공단으로 출결 내역 제출 버튼 클릭
"강의 별 출결 페이지" -> "구름 출결 본인인증 시스템": 해당 강의 출결 정보 전송 요청
"구름 출결 본인인증 시스템" --> "한국산업인력공단 시스템" : 강의 별 수강생 출결 정보를 CSV 형식으로 전송
note right: e.g.) \n "{강의명,강좌명,수강생 명,출석여부,출석시간,퇴장시간,휴대폰 번호}"
"구름 출결 본인인증 시스템" --> "강의 별 출결 페이지" : 전송 성공 메세지
"강의 별 출결 페이지" --> "채널 관리자": 전송 완료 메세지 팝업
end

@enduml