@startuml

title 1. 강의 수강시 GoormAuth 시퀀스 다이어그램

actor KDigital_trainee
box GoormChannelService
participant GoormAuth
participant GoormPublic_mOTP_module
endbox
box 외부인증모듈
participant mOTP
participant 타사본인인증모듈
endbox
box GoormChannelService
participant Channel수강생페이지
endbox

KDigital_trainee -> GoormAuth : 인증 요청
GoormAuth -> mOTP : Client의 인증 정보를 전달

alt 인증 성공
mOTP --> GoormAuth : 인증 성공 응답 제공 (200 OK)
GoormAuth --> KDigital_trainee : 인증 성공 메시지 전달 후 Channel 페이지로 연결
KDigital_trainee -> Channel수강생페이지 : 강의 정보 요청
Channel수강생페이지 --> KDigital_trainee : 강의 정보 페이지 반환

else 인증 실패
mOTP --> GoormAuth : 인증 실패 응답 제공 (4xx/5xx ERROR)
GoormAuth --> KDigital_trainee: 타사 본인인증 모듈로 연결하여 다른 방식으로 본인인증 할 수 있게 유도
KDigital_trainee -> 타사본인인증모듈: 본인인증 요청
end

@enduml