@startuml

title (UC06-2) 강의자 소개 페이지 조회자는 강의자를 구독하여 신규 오픈 강좌 및 강좌 할인 관련 알림을 받을 수 있다.
actor "강의자 소개 페이지 조회자"

box "구름 알림 메뉴"
participant "구름에듀 홈페이지"
participant "강좌 상세 페이지"

group [Case1] 신규 강좌 관련 알림 받는 경우
"강의자 소개 페이지 조회자" -> "강좌 상세 페이지" : 홈페이지 헤더 알림 버튼 클릭
note right
"강의자의 신규 강좌가 오픈하였습니다."라는 알림
end note
"강좌 상세 페이지" --> "강의자 소개 페이지 조회자" : 신규 오픈 강좌 정보 제공
end

group [Case2] 강좌 할인 알림 받는 경우
"강의자 소개 페이지 조회자" -> "강좌 상세 페이지" : 홈페이지 헤더 알림 버튼 클릭
note right
"강의자의 강좌가 할인을 시작했습니다."라는 알림
end note
"강좌 상세 페이지" --> "강의자 소개 페이지 조회자" : 강좌 할인율 및 할인 가격 정보 제공
end

@enduml