@startuml

title (UC06-3) 강의자 소개 페이지 조회자는 강의자를 구독하여 신규 공지 관련 알림을 받을 수 있다.
actor "강의자 소개 페이지 조회자"

box "구름 알림 메뉴"
participant "구름에듀 홈페이지"
participant "수강 페이지 - 공지사항 상세 페이지"
endbox

"강의자 소개 페이지 조회자" -> "수강 페이지 - 공지사항 상세 페이지" : 홈페이지 헤더 알림 버튼 클릭
note left
강의자 소개 페이지 구독 중이면서
해당 강좌를 수강 중인 경우만 알림 전송
end note
"수강 페이지 - 공지사항 상세 페이지" --> "강의자 소개 페이지 조회자" : 강의자가 게시한 공지사항 내용 제공


@enduml