@startuml

title (UC06-1) 강의자 소개 페이지 조회자는 강의자를 구독하여 강좌 쿠폰 발급 관련 알림을 받을 수 있다.
actor "강의자 소개 페이지 조회자"

box "강좌 쿠폰 발급 알림 메뉴"
participant "구름에듀 홈페이지"
participant "쿠폰 발급 모달"
endbox
participant "강좌 상세 페이지"
participant "강좌 결제 페이지"

"강의자 소개 페이지 조회자" -> "쿠폰 발급 모달" : 홈페이지 헤더 쿠폰 알림 버튼 클릭
note bottom
쿠폰 발급 시 쿠폰 알림에
신규 알림 개수 표시
end note
"쿠폰 발급 모달" --> "강의자 소개 페이지 조회자" : 사용 가능한 모든 쿠폰에 대해 [강좌명, 사용 기간, 결제하러 가기 버튼]을 리스트로 표시

group [쿠폰 사용 Scenario 1] 강의자 소개 페이지 조회자가 쿠폰 발급 모달에서 바로 결제하러 가는 경우

note right
모달 진입 시점 기준으로
처음 보는 발급 쿠폰 내역에 new 배지 노출
재 진입 시 new 배지 미노출
end note

"쿠폰 발급 모달" -> "강좌 결제 페이지" : 리스트에서 [결제하러 가기 버튼] 클릭
"강좌 결제 페이지" --> "강의자 소개 페이지 조회자" : 결제 페이지의 결제 금액에 해당 쿠폰 할인이 즉시 적용되어 표시
end

group [쿠폰 사용 Scenario 2] 강의자 소개 페이지 조회자가 쿠폰 발급 모달에서 강좌 상세 페이지로 이동 후 결제하는 경우
"쿠폰 발급 모달" -> "강좌 상세 페이지" : 리스트에서 [강좌명] 클릭
"강좌 상세 페이지" --> "강의자 소개 페이지 조회자" : 강좌 상세 정보 제공
"강좌 상세 페이지" -> "강좌 결제 페이지" : 결제하기 버튼 클릭
"강좌 결제 페이지" --> "강의자 소개 페이지 조회자" : 결제 페이지의 결제 금액에 해당 쿠폰 할인이 즉시 적용되어 표시
end

@enduml

