@startuml

title (UGA1) 모든 채널의 본인인증 설정 페이지에 접근할 수 있다.

actor "구름 Admin 관리자"

box "구름 채널 관리자 메뉴"
participant "본인 인증 페이지 - 메인"
endbox

"구름 Admin 관리자" -> "본인 인증 페이지 - 메인" : 1. 접근
"본인 인증 페이지 - 메인" --> "구름 Admin 관리자" : 2. 채널 검색창 및 채널 리스트 제공
"구름 Admin 관리자" -> "본인 인증 페이지 - 메인" : 3. 채널 검색 및 선택
"본인 인증 페이지 - 메인" --> "구름 Admin 관리자" : 4. 선택된 채널에 대해 \n"본인 인증 페이지 - 인증 적용", \n "본인 인증 페이지 - 인증 완료여부 조회"\n 페이지 제공

@enduml