@startuml

title (UCA1) 채널 Admin 관리자는 해당 채널의 모든 멤버에 대해 개별적으로 본인 인증이 1회 강제 되도록 설정할 수 있다.

actor "채널 Admin 관리자"

box "구름 채널 관리자 메뉴"
participant "본인 인증 페이지 - 메인"
participant "본인 인증 페이지 - 인증 적용"
endbox

"채널 Admin 관리자" -> "본인 인증 페이지 - 메인" : 인증 적용 버튼 선택
note left
"본인 인증 페이지 - 메인"에서
"인증 적용" 페이지가 기본 페이지로 설정되어 있으나
편의상 적용 버튼 선택으로 표현
end note


alt [Scenario 1] 개별 멤버에 대한 본인 인증 설정 on / off 하는 경우
"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 적용" : 1. 접근
"본인 인증 페이지 - 인증 적용" --> "채널 Admin 관리자" : 2. 모든 멤버에 대해 [이름, 로그인 아이디, 이메일, 사용자 권한, 본인 인증]를 리스트로 표시
"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 적용" : 3. 리스트 항목 옆 **[본인인증 적용하기] 토글**을 on /off
"본인 인증 페이지 - 인증 적용" -> "본인 인증 페이지 - 인증 적용" : 4. on / off 상태에 따라 해당 멤버에게 본인 인증 강제 혹은 해제
end

alt [Scenario 2] 전체 멤버에 대해 일괄로 본인 인증 설정 on / off 하는 경우
"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 적용" : 1. 페이지 최상단에 **[본인인증 일괄적용하기] 토글**을 on / off
"본인 인증 페이지 - 인증 적용" -> "본인 인증 페이지 - 인증 적용" : 2. on / off 상태에 따라 모든 멤버에게 본인 인증 강제 혹은 해제
"본인 인증 페이지 - 인증 적용" --> "채널 Admin 관리자" : 3. 2.의 결과가 갱신된 멤버 리스트 제공
end
@enduml