@startuml

title (UCA2) 해당 채널의 모든 구성원을 대상으로 본인 인증 완료 여부를 조회할 수 있다.

actor "채널 Admin 관리자"

box "구름 채널 관리자 메뉴"
participant "본인 인증 페이지 - 메인"
participant "본인 인증 페이지 - 인증 완료여부 조회"
endbox

"채널 Admin 관리자" -> "본인 인증 페이지 - 메인" : 인증 완료여부 조회 버튼 선택


alt [Scenario 1] 상단 필터가 전체 멤버인 경우

"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 완료여부 조회" : 접근
"본인 인증 페이지 - 인증 완료여부 조회" --> "채널 Admin 관리자" : 멤버 유형에 따라 다른 정보를 리스트로 표시

alt (멤버 유형 1) 본인인증 완료 멤버의 경우
"본인 인증 페이지 - 인증 완료여부 조회" --> "채널 Admin 관리자" : [이름, 로그인 아이디, 이메일, 사용자 권한, 본인 인증 완료 여부, 실명, 휴대폰 번호] 제공
note right
"본인 인증 완료 여부"는 "완료"로 표시
end note

end

alt (멤버 유형 2) 본인인증 미완료 멤버의 경우
"본인 인증 페이지 - 인증 완료여부 조회" --> "채널 Admin 관리자" : [이름, 로그인 아이디, 이메일, 사용자 권한, 본인 인증 완료 여부] 제공
note right
"본인 인증 완료 여부"는 "미완료"로 표시
end note
end

end

alt [Scenario 2] 상단 필터가 "본인 인증 완료 멤버만 표시"인 경우
"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 완료여부 조회" : 상단 필터를 "본인 인증 완료 멤버만 표시" 로 선택
"본인 인증 페이지 - 인증 완료여부 조회" --> "채널 Admin 관리자" : 본인 인증 완료된 모든 멤버 정보를 리스트로 표시
end

alt [Scenario 3] 상단 필터가 "본인 인증 미완료 멤버만 표시"인 경우
"채널 Admin 관리자" -> "본인 인증 페이지 - 인증 완료여부 조회" : 상단 필터를 "본인 인증 미완료 멤버만 표시" 로 선택
"본인 인증 페이지 - 인증 완료여부 조회" --> "채널 Admin 관리자" : 본인 인증 미완료된 모든 멤버 정보를 리스트로 표시
end

@enduml
