@startuml

title (UCM1) 본인 인증이 강제된 채널에 가입한 경우 구름 스쿨 로그인 시 팝업창을 통해 본인 인증을 진행할 수 있다.

actor "구름 스쿨 회원"

box "구름 스쿨 모듈"
participant "구름 스쿨 메인 페이지"
participant "Public mOTP 연동모듈"
endbox

box "외부 본인인증 시스템"
participant mOTP
participant "2차 본인인증모듈"
endbox

"구름 스쿨 회원" -> "구름 스쿨 메인 페이지" : 로그인

group [Scenario 1] 채널에 가입 요청 했지만 관리자가 미수락한 경우
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원" : 로그인 성공 페이지 제공
end

group [Scenario 2] 채널에 가입 후 본인 인증 미완료

"구름 스쿨 메인 페이지" --> "구름 스쿨 회원" : 본인 인증 안내 팝업 표시 및 본인 인증 페이지로 리디렉션
"구름 스쿨 회원" -> "Public mOTP 연동모듈" : 본인 인증 페이지로 진입
"Public mOTP 연동모듈" -> mOTP : 본인 인증 요청

group [성공 Case 1] mOTP 인증 성공 시
mOTP --> "Public mOTP 연동모듈" : 인증 성공 메세지
"Public mOTP 연동모듈" --> "구름 스쿨 메인 페이지" : 인증 성공 메세지
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원": 인증 성공 안내

end
group [성공 Case 2] mOTP 인증 실패 후 2차 본인인증 성공 시
mOTP --> "Public mOTP 연동모듈" : 인증 실패 메세지
"Public mOTP 연동모듈" -> "2차 본인인증모듈" : 인증 요청
note right: mOTP 인증 실패 시 다날로\n 2차 인증 시도
"2차 본인인증모듈" --> "Public mOTP 연동모듈" : 인증 성공 메세지
"Public mOTP 연동모듈" --> "구름 스쿨 메인 페이지" : 인증 성공 메세지
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원": 인증 성공 안내
end

group [실패 Case] mOTP 인증과 2차 본인인증 모두 실패
mOTP --> "Public mOTP 연동모듈" : 인증 실패 메세지
"Public mOTP 연동모듈" -> "2차 본인인증모듈" : 인증 요청
"2차 본인인증모듈" --> "Public mOTP 연동모듈" : 인증 실패 메세지
"Public mOTP 연동모듈" --> "구름 스쿨 메인 페이지" : 인증 실패 메세지
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원": 인증 실패 안내 및 재시도 요청
end

end

group [Scenario 3] 채널 가입 후 본인 인증 완료된 경우
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원" : 로그인 성공 페이지 제공
end

group [Scenario 4] goormedu 계정 사용자가 다른 채널에서 본인 인증을 완료
"구름 스쿨 메인 페이지" --> "구름 스쿨 회원" : 로그인 성공 페이지 제공
end

@enduml